### PR TITLE
Start CI!

### LINKED ISSUE #44: 3 basic tests
I work for developer teams. I talk them into using the following zero-coverage tests in CI:

1. syntax check
2. coding standard (much more than how you indent your code!)
3. static analysis

It makes your code robust without writing a single test.
Please consider introducing all three.

### PR DESCRIPTION
**Pull request by szepeviktor**
@mnelson4 Here you go! :)

Closes #44

### CODE REVIEW

**Comment by szepeviktor** [comment]
Do you have capacity to follow WPCS?
The first big step could be made by running `vendor/bin/phpcbf`

**Comment by szepeviktor** [comment]
Also PHPStan level 0 is for broken software, 2 or 4 looks normal :)

**Comment by szepeviktor** [comment]
Done. All green 🍏

**Comment by mnelson4** [comment]
Awesome. But I think I'd rather use PSR-12 coding standards rather the WP ones (I'm more accustomed to those I think). Is that an easy change?

**Comment by szepeviktor** [comment]
Done.

Coding style is habit of Mike :)

**Comment by mnelson4** [comment]
Yeah those coding standards look more like what I'm already doing, great.

I'd like to avoid accidentally committing all these composer files to the git repo, and the WordPress SVN repo.
I was going to add a `.gitignore` file like this:

```
vendor/
!vendor/autoloader.php
!vendor/composer
```
so the git repo will ignore everything in the vendor folder except composer's autoloader, but then I noticed the files in `vendor/composer` get modified when I run `composer install` and I think I'd rather not commit those changes by accident. What would you recommend?

And for the SVN repo, it will be a bit of a pain to SVN ignore all the files (and I'm sure I'll forget to manually remove them). How would you suggest preventing accidentally committing the files in `vendor` to the SVN repo? I suppose I'll need a build process or something like https://github.com/WordPress/wp-lazy-loading/pull/13

**Comment by szepeviktor** [comment]
> I'll need a build process

Yes!

1. Keep only source code in this repo, no generated code
1. Have an automatic build process
1. And a manual CI action to deploy to WP.org

**Comment by szepeviktor** [comment]
When you release your plugin you may upload the built ZIP to GitHub releases.

**Comment by mnelson4** [comment]
I think I’m going to wang to use Gulp for building, as I’m hoping to add Freemius integration and there’s a gulp-Freemius package https://freemius.com/help/documentation/selling-with-freemius/deployment/

**Comment by szepeviktor** [comment]
As far as I know the only thing to build/generate is the Composer autoloader.

**Comment by mnelson4** [comment]
Oh right— the other built things are just necessary for running those automated tests which Travis is already doing, so I don’t even need to run those locally...

**Comment by mnelson4** [comment]
FYI this got an honourable mention in my monthly transparency report: https://cmljnelson.blog/2020/02/04/print-my-blog-transparency-report-january-2020/#autoloading-and-code-cleanup-with-viktor-svepe

**Comment by szepeviktor** [comment]
Thank you Mike.

**Comment by szepeviktor** [comment]
@mnelson4 Could you put a _hotfix_ on my name?

**Comment by mnelson4** [comment]
hotfix released! My apologies... admittedly a lot of my blogging has recently happened at 5am...😝

**Pull request merged**
