### PR TITLE
Proper autoloading

### PR DESCRIPTION
**Pull request by szepeviktor**
PSR-4
```
src/PrintMyBlog/controllers/PmbGutenbergBlock.php
src/PrintMyBlog/controllers/PmbFrontend.php
src/PrintMyBlog/controllers/PmbActivation.php
src/PrintMyBlog/controllers/PmbInit.php
src/PrintMyBlog/controllers/PmbCommon.php
src/PrintMyBlog/controllers/PmbAjax.php
src/PrintMyBlog/controllers/PmbAdmin.php
src/PrintMyBlog/domain/FrontendPrintSettings.php
src/PrintMyBlog/domain/PrintOptions.php
src/mnelson4/RestApiDetector.php
src/mnelson4/RestApiDetectorError.php
src/Twine/controllers/BaseController.php
src/Twine/admin/news/DashboardNews.php
```

@mnelson4  Composer is not required to use this plugin, only its autoloader is included.

### CODE REVIEW

**Comment by szepeviktor** [comment]
It is super nice to strip `Pmb` prefixes from class names as they are already in the PrintMyBlog namespace.

**Comment by mnelson4** [comment]
Thanks @szepeviktor I think this is a really good change. It's not strictly backwards compatible though, which I'm OK with seeing how I highly doubt any other devs are using this version. So it will probably require bumping the version from 2.1.1 to 3.0.0, which is fine.
BUT do you think you'd like to introduce any more backwards-incompatible changes in the near future? If so it might be nice to lump them into here now. If you don't plan on any other major changes in the next few weeks, we can move ahead with these...

And ya, if we will be using proper namespacing, the `Pmb` prefix won't be necessary...

**Comment by szepeviktor** [comment]
Actually I am not a PMB user :)

This PR advertises PHPStan.

**Comment by mnelson4** [comment]
oook. Phew! that's a lot of work to let me know about PHPStan. But now I do!

**Comment by szepeviktor** [comment]
It you repeat the same procedure 50× it seems small.

**Comment by szepeviktor** [comment]
@mnelson4 Could you repeat the merging here?

**Comment by mnelson4** [comment]
Yeah I hope to but this will be a bigger review, some more work, and especially a major version bump (which may scare some users away, although I'm considering doing it just as an experiment.)

**Comment by szepeviktor** [comment]
This PR contains

- removed require_once-s
- added Composer config+autoloader

**Comment by mnelson4** [comment]
I see this adds support for PHPstan and your PHPStan for WordPress is meant to make it work for WordPress, but when I run `composer install; composer update --optimize-autoloader; ./vendor/phpstan analyse src` it works but I get a bunch of errors about WordPress core functions not being recognized. Eg

```
vendor\bin\phpstan.bat analyse src
 14/14 [============================] 100%

 ------ -------------------------------------------
  Line   PrintMyBlog\controllers\PmbActivation.php
 ------ -------------------------------------------
  27     Function add_action not found.
  37     Function current_user_can not found.
  37     Function get_option not found.
  38     Function update_option not found.
  43     Function wp_redirect not found.
  44     Function add_query_arg not found.
  48     Function admin_url not found.
 ------ -------------------------------------------
```
Is that expected or is something not setup properly?

**Comment by szepeviktor** [comment]
> Is that expected or is something not setup properly?

PHPStan need to be configured.
https://github.com/szepeviktor/phpstan-wordpress/blob/master/example/phpstan.neon.dist

At least my extension needs to be loaded with `includes:`

**Comment by mnelson4** [comment]
Ok I'll have to look into that later; at very least adding autoloading is a nice benefit, and I bet composer will come in handy. I do think I'm going to need to look into adding webpack or gulp next for packaging everything up for each release (I used to be able to just copy everything except the .git folder and send it to the WP SVN plugin repo).
Thanks I've merged this into master and will release hopefully this evening.

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
> just copy everything

software development should include quality assurance
please consider introducing those 3 basic tests and avoid putting code in the repo without them

**Comment by szepeviktor** [comment]
any CI could include a manual WP.org release action...

**Pull request merged**
