### PR TITLE
Healing HTML

### LINKED ISSUE #53: Make our HTML standard compliant
kép

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #53 

Please consider

- avoiding if+for as building blocks https://www.youtube.com/watch?v=crSUWtRYw-M
- naming things currently named generally, e.g. `$data` or value, return, output
- converting data between languages, e.g. in PHP->HTML use esc_* functions, in string->URL use add_query_arg
- [avoiding patterns](https://github.com/object-calisthenics/phpcs-calisthenics-rules#2-do-not-use-else-keyword) like: [if() return else return](https://github.com/jupeter/clean-code-php#avoid-nesting-too-deeply-and-return-early-part-1)

Building HTML in PHP: https://github.com/szepeviktor/Toolkit4WP/blob/master/src/helpers.php#L17-L28
...in a professional way: https://github.com/decodelabs/tagged

### CODE REVIEW

**Comment by szepeviktor** [comment]
❗️ My example does not work.

```php
$url = sprintf(
                        $base_url,
                        $slug,
                        $post->ID
                    );
```

This should also be add_query_arg without printf placeholders.

**Comment by mnelson4** [comment]
Thanks for the suggestion. I switched master to use `add_query_arg`, `esc_html` and `esc_url`, although it seems to still be producing URLs that don't have the ampersands escaped...

**Comment by szepeviktor** [comment]
`esc_url(add_query_arg())` produces HTML-encoded URL-s.

**Comment by szepeviktor** [comment]
```
var_dump(esc_url(add_query_arg(["other"=>"jump"], "http://example.com?alma=beach")));

string(45) "http://example.com?alma=beach&#038;other=jump"
```

**Pull request closed without merging**
